"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:blue)\
$docker_context\
$kubernetes\
[](fg:blue bg:purple)\
$time\
[ ](fg:purple)\
$line_break$character"""

palette = 'tokyo_night'

[palettes.tokyo_night]
red      = "#f7768e"
orange   = "#ff9e64"
yellow   = "#e0af68"
green    = "#9ece6a"
cyan     = "#7dcfff"
blue     = "#7aa2f7"
purple   = "#9d7cd8"
magenta  = "#bb9af7"
text     = "#c0caf5"
subtext1 = "#a9b1d6"
subtext0 = "#9aa5ce"
overlay1 = "#565f89"
surface2 = "#545c7e"
surface1 = "#3b4261"
surface0 = "#292e42"
base     = "#1a1b26"
mantle   = "#16161e"
crust    = "#0f0f17"
# format role aliases
peach    = "#ff9e64"
teal     = "#7dcfff"
mauve    = "#bb9af7"
lavender = "#9d7cd8"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Linux = "󰌽"
Pop = ""

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"git" = " "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $context) ](fg:base bg:blue)]($style)'

[kubernetes]
disabled = true
symbol = "󱃾 "
style = "bg:blue"
format = '[[ $symbol$context(:$namespace) ](fg:base bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:purple"
format = '[[  $time ](fg:base bg:purple)]($style)'

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'

[cmd_duration]
min_time = 500
style = "fg:yellow"
format = ' took [$duration]($style) '
