"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0)\
$directory\
[](fg:peach bg:green)\
$git_branch\
$git_status\
[](fg:green bg:teal)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:blue)\
$docker_context\
$kubernetes\
[](fg:blue bg:purple)\
$time\
[ ](fg:purple)\
$line_break$character"""

palette = 'gruvbox'

[palettes.gruvbox]
red      = "#fb4934"
orange   = "#fe8019"
yellow   = "#fabd2f"
green    = "#b8bb26"
aqua     = "#8ec07c"
blue     = "#83a598"
purple   = "#d3869b"
gray     = "#928374"
text     = "#ebdbb2"
subtext1 = "#d5c4a1"
subtext0 = "#bdae93"
overlay1 = "#928374"
surface2 = "#665c54"
surface1 = "#504945"
surface0 = "#3c3836"
base     = "#282828"
mantle   = "#1d2021"
crust    = "#1d2021"
# format role aliases
peach    = "#fe8019"
teal     = "#8ec07c"
mauve    = "#d3869b"
lavender = "#d3869b"

[os]
disabled = false
style = "bg:surface0 fg:text"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
Macos = "󰀵"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Linux = "󰌽"
Pop = ""

[username]
show_always = true
style_user = "bg:surface0 fg:text"
style_root = "bg:surface0 fg:red"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"git" = " "

[git_branch]
symbol = ""
style = "bg:green"
format = '[[ $symbol $branch ](fg:base bg:green)]($style)'

[git_status]
style = "bg:green"
format = '[[($all_status$ahead_behind )](fg:base bg:green)]($style)'

[nodejs]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[c]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[rust]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[golang]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[php]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[java]
symbol = " "
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[kotlin]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[haskell]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[python]
symbol = ""
style = "bg:teal"
format = '[[ $symbol( $version) ](fg:base bg:teal)]($style)'

[docker_context]
symbol = ""
style = "bg:blue"
format = '[[ $symbol( $context) ](fg:base bg:blue)]($style)'

[kubernetes]
disabled = true
symbol = "󱃾 "
style = "bg:blue"
format = '[[ $symbol$context(:$namespace) ](fg:base bg:blue)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:purple"
format = '[[  $time ](fg:base bg:purple)]($style)'

[line_break]
disabled = false

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❮](bold green)'

[cmd_duration]
min_time = 500
style = "fg:yellow"
format = ' took [$duration]($style) '
